### ISSUE TITLE
💡Comment : "user 도메인 가이드 라인 작성"

### ISSUE THREAD

**Issue by sinwoongkang1** [ToastitProject/Toastit#101]
## 📄 어떤 기능인가요?
주석 추가 및 사용되지 않는 코드 삭제하였습니다

## ✔️ TO-DO
- [ ] 컨트롤러에 주석 추가하기
- [ ] 서비스에 주석 추가하기
- [ ] log.info -> log.debug 변경하기
