### ISSUE TITLE
♻️ Refactor : "seasonalcocktail 도메인 서비스 리팩토링"

### ISSUE THREAD

**Issue by CodeJesterND** [ToastitProject/Toastit#84]
## 📄 작업 내용
- 전체적인 패키지 구조 조정이 진행될 예정입니다 :)

## ✔️ TO-DO
- [x] 도메인 이름 변경
- [x] 패키지 구조 개선
- [x] 전체적인 코드 리팩토링
- [x] 컨트롤러 가독성과 의미있는 코드 배치 진행
- [ ] 디자인 위치 조정 및 기능 업데이트 예정

## 🔔 기타
- 아직은 월별 숫자를 기준으로 칵테일을 무작위로 뽑아오고 있습니다 :) 
- 추후 계절에 관련된 재료 위주로 추천해줄 예정 입니다.
