### ISSUE TITLE
♻️ Refactor : "image 도메인 서비스 리팩토링"

### ISSUE THREAD

**Issue by CodeJesterND** [ToastitProject/Toastit#92]
## 📄 작업 내용
- 전체적인 패키지 구조 조정이 진행될 예정입니다 :)

## ✔️ TO-DO
- [x] 도메인 이름 변경
- [x] 패키지 구조 개선
- [ ] 전체적인 코드 리팩토링
- [ ] 컨트롤러 가독성과 의미있는 코드 배치 진행
- [ ] 디자인 위치 조정 및 기능 업데이트 예정

## 🔔 기타
- 도메인과 엔티티의 개념을 확실히 짚어서 리팩토링할 예정입니다 :)
