### ISSUE TITLE
✨ Feat : 네이버 통합검색 API 를 활용한 메인화면 칵테일 배치

### ISSUE THREAD

**Issue by sinwoongkang1** [ToastitProject/Toastit#99]
## 📄 어떤 기능인가요?
1.네이버 통합검색 API 요청을 작성합니다. (각 칵테일 별)
2.각 칵테일 별로 2달전 1달전 검색량 을 가져와 변화량을 측정합니다.
3.변화량이 양의 값으로 가장 많은 칵테일을 5개 가져옵니다.
4.메인화면 view 에 표시 합니다

## ✔️ TO-DO
- [x] TrendCocktail 클래스, 레포지토리, 서비스, DTO, 엔티티 생성
- [x] Naver 통합검색 API key 발급받기
- [ ] API 요청문 작성하기
- [ ] 응답 엔드포인트에서 서버로 응답 전송하기
- [ ] 서버에서 받은 데이를 DB에 저장하기
- [ ] DB 에 저장된 2달전, 1달전 데이터의 값 차이를 조회하는 쿼리문 작성하기
- [ ] 컨트롤러에서 5개의 칵테일 view 로 전송하기
- [ ] 메인화면 출력 및 CSS 수정

## 🔔 기타

API 그대로 사용하지 않기
엔드포인트에서 서버로 데이터를 전송할 때 자동으로 전송하는 방법 찾아보기
새로운 검색량을 받을 때 DB에 업데이트 하는 법 찾기
